# Make sure we’re using the latest Homebrew
update

# Use most recent version of vim
install vim --override-system-vi

# for a sane tmux <--> OSX clipboard service
# http://robots.thoughtbot.com/tmux-copy-paste-on-os-x-a-better-future
install tmux
install reattach-to-user-namespace

# install source control systems
install git
install mercurial
install subversion

# install youtube-dl and dependencies for post processing
install youtube-dl
install ffmpeg

install z

# install JavasScript related stuff
install node
install casperjs
install phantomjs
install slimerjs

# install databases
install couchdb
install mysql
install postgresql
install redis

# Remove outdated versions from the cellar
cleanup
